.PHONY: setup test dev docker-build docker-run

setup:
	bash scripts/setup.sh

test:
	bash scripts/test.sh

dev:
	bash scripts/dev.sh

docker-build:
	bash scripts/docker-build.sh

docker-run:
	bash scripts/docker-run.sh