services:
  app:
    build: .
    container_name: task-collector-app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    container_name: task-collector-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    container_name: task-collector-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tasks"]
      interval: 5s
      timeout: 5s
      retries: 10